[package]
name = "governance_contract"
version = "0.1.0"
edition = "2021"

[dependencies]
cosmwasm-std = { version = "0.14", default-features = false }
cw-storage-plus = "0.8"
serde = { version = "1.0", features = ["derive"] }
schemars = "0.8"
